import type { GalleryImage } from "./types";

export const galleryImages: GalleryImage[] = [
  {
    id: "hero-beach",
    src: "/gallery/hero-beach-formentera.jpg",
    alt: "Beautiful beach on Formentera island with turquoise waters",
    category: "destinations",
    caption: "Your dream vacation awaits",
  },
  {
    id: "cabo-sandos",
    src: "/gallery/girls-trip-2_orig.jpg",
    alt: "Group travel promotion for Sandos Finisterra Los Cabos",
    category: "all-inclusive",
    caption: "Join us in Cabo at Sandos Finisterra Los Cabos",
  },
  {
    id: "couple-pool",
    src: "/gallery/couple-in-pool_orig.jpg",
    alt: "Couple relaxing in pool at all-inclusive resort",
    category: "all-inclusive",
    caption: "All-inclusive resort relaxation",
  },
  {
    id: "family-floating",
    src: "/gallery/family-floating_orig.jpg",
    alt: "Family floating together in tropical resort pool",
    category: "all-inclusive",
    caption: "Family-friendly all-inclusive fun",
  },
  {
    id: "destination-wedding",
    src: "/gallery/wedding_orig.jpeg",
    alt: "Destination wedding ceremony",
    category: "weddings",
    caption: "Destination wedding on the beach",
  },
  {
    id: "wedding-bg",
    src: "/gallery/destination-wedding-bg.jpeg",
    alt: "Romantic destination wedding setting",
    category: "weddings",
    caption: "Say 'I do' in paradise",
  },
  {
    id: "ocean-cruise",
    src: "/gallery/ocean-cruise-bg.jpg",
    alt: "Ocean cruise ship at sea",
    category: "cruises",
    caption: "Ocean cruising adventures",
  },
  {
    id: "river-cruise",
    src: "/gallery/river-cruise-bg.jpg",
    alt: "River cruise through scenic European landscape",
    category: "cruises",
    caption: "European river cruising",
  },
  {
    id: "perfect-day-cococay",
    src: "/gallery/perfect-day-cococay.jpg",
    alt: "Perfect Day at CocoCay private island",
    category: "cruises",
    caption: "Perfect Day at CocoCay, Bahamas",
  },
  {
    id: "river-scenic",
    src: "/gallery/river-cruise-scenic.jpg",
    alt: "Scenic river cruise comparison",
    category: "cruises",
    caption: "River cruise line options",
  },
  {
    id: "wine-country",
    src: "/gallery/wine-country.jpeg",
    alt: "Napa and Sonoma wine country vineyards",
    category: "europe",
    caption: "California wine country",
  },
  {
    id: "group-travel",
    src: "/gallery/group-travel_orig.jpg",
    alt: "Group of travelers on vacation together",
    category: "destinations",
    caption: "Group travel made easy",
  },
  {
    id: "voluntourism",
    src: "/gallery/voluntourism.jpg",
    alt: "Blue Water Travel voluntourism trip in Mexico",
    category: "destinations",
    caption: "Voluntourism with purpose",
  },
  {
    id: "travel-dest-1",
    src: "/gallery/travel-dest-1.jpg",
    alt: "Tropical travel destination",
    category: "destinations",
    caption: "Explore the world with us",
  },
  {
    id: "travel-dest-2",
    src: "/gallery/travel-dest-2.jpg",
    alt: "Scenic vacation destination",
    category: "destinations",
    caption: "Unforgettable getaways",
  },
  {
    id: "travel-dest-3",
    src: "/gallery/travel-dest-3.jpg",
    alt: "Beach vacation destination",
    category: "all-inclusive",
    caption: "Caribbean paradise",
  },
  {
    id: "travel-dest-4",
    src: "/gallery/travel-dest-4.jpg",
    alt: "Resort destination view",
    category: "all-inclusive",
    caption: "Resort escape",
  },
  {
    id: "travel-dest-5",
    src: "/gallery/travel-dest-5.jpg",
    alt: "Travel adventure destination",
    category: "destinations",
    caption: "Adventure awaits",
  },
  {
    id: "travel-dest-6",
    src: "/gallery/travel-dest-6.jpg",
    alt: "Vacation destination scenery",
    category: "destinations",
    caption: "Travel inspiration",
  },
  {
    id: "terri-jobe",
    src: "/team/terri-jobe.jpg",
    alt: "Terri Jobe, Owner and Lead Travel Advisor at Blue Water Travel",
    category: "team",
    caption: "Terri Jobe — Owner & Lead Advisor",
  },
  {
    id: "ig-hard-rock-punta-cana",
    src: "/social/ig-Daynva7pgXW.jpg",
    alt: "Hard Rock Punta Cana all-inclusive resort in the Dominican Republic",
    category: "all-inclusive",
    caption: "Hard Rock Punta Cana — DR resort review",
  },
  {
    id: "ig-dreams-cap-cana",
    src: "/social/ig-Dafoadjh8ov.jpg",
    alt: "Dreams Cap Cana all-inclusive resort for family vacations",
    category: "all-inclusive",
    caption: "Dreams Cap Cana — family reunion destination",
  },
  {
    id: "ig-destination-wedding",
    src: "/social/ig-DasgYzbJJRD.jpg",
    alt: "Unique destination wedding venue options beyond the beach",
    category: "weddings",
    caption: "Destination weddings — rooftops, gardens & floating decks",
  },
  {
    id: "ig-lake-lotawana",
    src: "/social/ig-DaaacrTTh1i.jpg",
    alt: "Lake Lotawana Missouri scenic view at sunset",
    category: "destinations",
    caption: "Unforgettable moments at Lake Lotawana",
  },
  {
    id: "ig-joie-highlight",
    src: "/social/ig-DbBW421xYaI.jpg",
    alt: "Joie Reardon, Blue Water Travel agent highlight",
    category: "team",
    caption: "Joie Reardon — Travel Agent",
  },
  {
    id: "fb-wedding-table-flowers",
    src: "/social/fb-wedding-table-flowers.jpg",
    alt: "Destination wedding reception table with floral centerpiece",
    category: "weddings",
    caption: "Destination wedding table setting — from Blue Water Travel Facebook",
  },
  {
    id: "fb-wedding-ceremony-1",
    src: "/social/fb-wedding-ceremony-1.jpg",
    alt: "Destination wedding ceremony",
    category: "weddings",
    caption: "Destination wedding ceremony — Blue Water Travel Facebook",
  },
  {
    id: "fb-wedding-ceremony-2",
    src: "/social/fb-wedding-ceremony-2.jpg",
    alt: "Outdoor destination wedding ceremony",
    category: "weddings",
    caption: "Beach or garden destination wedding — Blue Water Travel Facebook",
  },
  {
    id: "fb-wedding-ceremony-3",
    src: "/social/fb-wedding-ceremony-3.jpg",
    alt: "Destination wedding celebration with guests",
    category: "weddings",
    caption: "Destination wedding celebration — Blue Water Travel Facebook",
  },
  {
    id: "fb-wedding-floral-detail",
    src: "/social/fb-wedding-floral-detail.jpg",
    alt: "Wedding floral arrangement detail",
    category: "weddings",
    caption: "Wedding floral details — Blue Water Travel Facebook",
  },
  {
    id: "fb-wedding-ceremony-4",
    src: "/social/fb-wedding-ceremony-4.jpg",
    alt: "Destination wedding ceremony moment",
    category: "weddings",
    caption: "Destination wedding moment — Blue Water Travel Facebook",
  },
  {
    id: "fb-wedding-detail",
    src: "/social/fb-wedding-detail.jpg",
    alt: "Destination wedding detail shot",
    category: "weddings",
    caption: "Destination wedding detail — Blue Water Travel Facebook",
  },
  {
    id: "fb-wedding-reception",
    src: "/social/fb-wedding-reception.jpg",
    alt: "Destination wedding reception",
    category: "weddings",
    caption: "Destination wedding reception — Blue Water Travel Facebook",
  },
  {
    id: "fb-erica-wild-highlight",
    src: "/social/fb-erica-wild-highlight.jpg",
    alt: "June Agent Highlight — Erica Wild, Travel Agent at Blue Water Travel",
    category: "team",
    caption: "Erica Wild — June Agent Highlight. Passionate about all-inclusive Caribbean travel and European adventures.",
  },
  {
    id: "fb-machu-picchu",
    src: "/social/fb-machu-picchu.jpg",
    alt: "Machu Picchu destination — Your reminder there is only 5 years left to walk and see Machu Picchu",
    category: "destinations",
    caption: "Machu Picchu, Peru — once-in-a-lifetime destination adventure",
  },
  {
    id: "fb-machu-picchu-2",
    src: "/social/fb-machu-picchu-2.jpg",
    alt: "Machu Picchu scenic view at Saqsaywaman",
    category: "destinations",
    caption: "Explore Machu Picchu with Blue Water Travel",
  },
  {
    id: "fb-viking-cruise",
    src: "/social/fb-viking-cruise.jpg",
    alt: "Viking river cruise promotion — I SELL VIKING",
    category: "cruises",
    caption: "Viking river cruises — book with Blue Water Travel",
  },
  {
    id: "fb-celebrity-cruises-promo",
    src: "/social/fb-celebrity-cruises-promo.jpg",
    alt: "Celebrity Cruises free prepaid gratuities promotion with Blue Water Travel",
    category: "cruises",
    caption: "Celebrity Cruises — free prepaid gratuities exclusive with Blue Water Travel",
  },
  {
    id: "fb-fishing-fathers-day",
    src: "/social/fb-fishing-fathers-day.jpg",
    alt: "Deep sea fishing trip — Father's Day adventure idea",
    category: "destinations",
    caption: "Deep sea fishing adventures — don't be basic for Father's Day!",
  },
  {
    id: "fb-fishing-fathers-day-2",
    src: "/social/fb-fishing-fathers-day-2.jpg",
    alt: "Fishing boat excursion promotion",
    category: "destinations",
    caption: "Book a fishing excursion with Blue Water Travel",
  },
  {
    id: "fb-wedding-monument",
    src: "/social/fb-wedding-monument.jpg",
    alt: "Destination wedding at a historic monument setting",
    category: "weddings",
    caption: "Unique destination wedding venues — Blue Water Travel Facebook",
  },
  {
    id: "fb-wedding-twilight",
    src: "/social/fb-wedding-twilight.jpg",
    alt: "Destination wedding at twilight",
    category: "weddings",
    caption: "Twilight destination wedding moment",
  },
  {
    id: "fb-wedding-tree",
    src: "/social/fb-wedding-tree.jpg",
    alt: "Outdoor destination wedding among trees",
    category: "weddings",
    caption: "Garden destination wedding setting",
  },
  {
    id: "fb-wedding-reception-lighting",
    src: "/social/fb-wedding-reception-lighting.jpg",
    alt: "Destination wedding reception with candle lighting",
    category: "weddings",
    caption: "Elegant destination wedding reception lighting",
  },
  {
    id: "fb-panama-casco-viejo-flag",
    src: "/social/fb-panama-casco-viejo-flag.jpg",
    alt: "Panama flag hanging across a historic street in Casco Viejo with colonial buildings and outdoor café",
    category: "destinations",
    caption: "Casco Viejo, Panama City — historic streets and culture",
  },
  {
    id: "fb-colonial-destination-building",
    src: "/social/fb-colonial-destination-building.jpg",
    alt: "Grand white colonial-style destination building framed by palm trees under a blue sky",
    category: "destinations",
    caption: "Colonial architecture at a featured travel destination",
  },
];

export const galleryCategories = [
  { id: "all", label: "All Photos" },
  { id: "all-inclusive", label: "All-Inclusive" },
  { id: "cruises", label: "Cruises" },
  { id: "europe", label: "Europe" },
  { id: "weddings", label: "Weddings" },
  { id: "destinations", label: "Destinations" },
  { id: "team", label: "Team" },
] as const;
