import type { GalleryImage } from "./types";

export const galleryImages: GalleryImage[] = [
  {
    id: "hero-beach",
    src: "/gallery/hero-beach-formentera.jpg",
    alt: "Beautiful beach on Formentera island with turquoise waters",
    category: "destinations",
    caption: "Your dream vacation awaits",
  },
  {
    id: "cabo-sandos",
    src: "/gallery/girls-trip-2_orig.jpg",
    alt: "Group travel promotion for Sandos Finisterra Los Cabos",
    category: "all-inclusive",
    caption: "Join us in Cabo at Sandos Finisterra Los Cabos",
  },
  {
    id: "couple-pool",
    src: "/gallery/couple-in-pool_orig.jpg",
    alt: "Couple relaxing in pool at all-inclusive resort",
    category: "all-inclusive",
    caption: "All-inclusive resort relaxation",
  },
  {
    id: "family-floating",
    src: "/gallery/family-floating_orig.jpg",
    alt: "Family floating together in tropical resort pool",
    category: "all-inclusive",
    caption: "Family-friendly all-inclusive fun",
  },
  {
    id: "destination-wedding",
    src: "/gallery/wedding_orig.jpeg",
    alt: "Destination wedding ceremony",
    category: "weddings",
    caption: "Destination wedding on the beach",
  },
  {
    id: "wedding-bg",
    src: "/gallery/destination-wedding-bg.jpeg",
    alt: "Romantic destination wedding setting",
    category: "weddings",
    caption: "Say 'I do' in paradise",
  },
  {
    id: "ocean-cruise",
    src: "/gallery/ocean-cruise-bg.jpg",
    alt: "Ocean cruise ship at sea",
    category: "cruises",
    caption: "Ocean cruising adventures",
  },
  {
    id: "river-cruise",
    src: "/gallery/river-cruise-bg.jpg",
    alt: "River cruise through scenic European landscape",
    category: "cruises",
    caption: "European river cruising",
  },
  {
    id: "perfect-day-cococay",
    src: "/gallery/perfect-day-cococay.jpg",
    alt: "Perfect Day at CocoCay private island",
    category: "cruises",
    caption: "Perfect Day at CocoCay, Bahamas",
  },
  {
    id: "river-scenic",
    src: "/gallery/river-cruise-scenic.jpg",
    alt: "Scenic river cruise comparison",
    category: "cruises",
    caption: "River cruise line options",
  },
  {
    id: "wine-country",
    src: "/gallery/wine-country.jpeg",
    alt: "Napa and Sonoma wine country vineyards",
    category: "europe",
    caption: "California wine country",
  },
  {
    id: "group-travel",
    src: "/gallery/group-travel_orig.jpg",
    alt: "Group of travelers on vacation together",
    category: "destinations",
    caption: "Group travel made easy",
  },
  {
    id: "voluntourism",
    src: "/gallery/voluntourism.jpg",
    alt: "Blue Water Travel voluntourism trip in Mexico",
    category: "destinations",
    caption: "Voluntourism with purpose",
  },
  {
    id: "travel-dest-1",
    src: "/gallery/travel-dest-1.jpg",
    alt: "Tropical travel destination",
    category: "destinations",
    caption: "Explore the world with us",
  },
  {
    id: "travel-dest-2",
    src: "/gallery/travel-dest-2.jpg",
    alt: "Scenic vacation destination",
    category: "destinations",
    caption: "Unforgettable getaways",
  },
  {
    id: "travel-dest-3",
    src: "/gallery/travel-dest-3.jpg",
    alt: "Beach vacation destination",
    category: "all-inclusive",
    caption: "Caribbean paradise",
  },
  {
    id: "travel-dest-4",
    src: "/gallery/travel-dest-4.jpg",
    alt: "Resort destination view",
    category: "all-inclusive",
    caption: "Resort escape",
  },
  {
    id: "travel-dest-5",
    src: "/gallery/travel-dest-5.jpg",
    alt: "Travel adventure destination",
    category: "destinations",
    caption: "Adventure awaits",
  },
  {
    id: "travel-dest-6",
    src: "/gallery/travel-dest-6.jpg",
    alt: "Vacation destination scenery",
    category: "destinations",
    caption: "Travel inspiration",
  },
  {
    id: "terri-jobe",
    src: "/team/terri-jobe.jpg",
    alt: "Terri Jobe, Owner and Lead Travel Advisor at Blue Water Travel",
    category: "team",
    caption: "Terri Jobe — Owner & Lead Advisor",
  },
];

export const galleryCategories = [
  { id: "all", label: "All Photos" },
  { id: "all-inclusive", label: "All-Inclusive" },
  { id: "cruises", label: "Cruises" },
  { id: "europe", label: "Europe" },
  { id: "weddings", label: "Weddings" },
  { id: "destinations", label: "Destinations" },
  { id: "team", label: "Team" },
] as const;
